name: my_health
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # utility packages
  http: ^1.1.0
  url_launcher: ^6.2.2
  logger: ^2.0.2+1
  intl: ^0.19.0
# icons packages

  iconsax: ^0.0.8
  # State management Get
  get: ^4.6.6
  get_storage: ^2.1.1

  # Page indicating
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  # Product specific

  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^2.24.2
  # loading
  lottie: ^2.7.0
  connectivity_plus: ^5.0.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  cached_network_image: ^3.3.1
  semicircle_indicator: ^1.1.1
  syncfusion_flutter_gauges: ^24.2.4
  dio: ^5.4.0
  typing_animation: ^0.0.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  hive_generator: ^2.0.1
  hive: ^2.2.3
  build_runner:
  syncfusion_flutter_charts: ^24.2.6
  icons_launcher: ^2.1.7




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/animations/onboarding/
    - assets/images/animations/
    - assets/images/animations/lotties/
    - assets/images/animations/categories/
    - assets/images/foods/
    - assets/images/drinks/
    - assets/images/doctors/
    - assets/Logos/

  fonts:
    - family: Gilroy
      fonts:
     
        - asset: assets/fonts/Gilroy-Medium.ttf 
      
        

 
  
 