// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Yd-JQEMOVK6GjZvMDbKH8Kwblua6EPI',
    appId: '1:128180657727:android:1201fb43a7f279bee6228a',
    messagingSenderId: '128180657727',
    projectId: 'my-health-1fc73',
    storageBucket: 'my-health-1fc73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzojyd9Lr9Tp2m0axnLUuPENcKH6P-kkE',
    appId: '1:128180657727:ios:8f9bede069135342e6228a',
    messagingSenderId: '128180657727',
    projectId: 'my-health-1fc73',
    storageBucket: 'my-health-1fc73.appspot.com',
    androidClientId: '128180657727-vgi6f724hk0lv16l7r4mpe8gltq2l79j.apps.googleusercontent.com',
    iosClientId: '128180657727-5tf9fn02k35bkn1nc81621ol3ns8j4ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHealth',
  );
}
